import React from "react";
import Head from "next/head";
import Link from "next/link";
import dynamic from "next/dynamic";

const PageWraper = dynamic(() => import("../../Layout/PageWraper"));

const Terms = () => {
  return (
    <PageWraper>
      <Head>
        <title>GoodTools.Ai - Terms & Conditions</title>
        <meta name="title" content="GoodTools.Ai - Terms & Conditions" />
        <meta
          name="description"
          content="Find the best AI tools for your needs. Go to the filterand choose your Category."
        />
        <meta
          name="keywords"
          content="Ai Tools, Best Ai Tools, Ai Tools Finder"
        />
        <meta name="robots" content="max-image-preview:large" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="English" />
        <meta property="og:title" content="GoodTools.Ai - Terms & Conditions" />
        <meta
          property="og:description"
          content="Find the best AI tools for your needs. Go to the filterand choose your Category."
        />
        <meta property="og:image" content="https://goodtools.ai/logo.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <div className="max-w-screen-xl mx-auto px-2 md:px-0 breadcrumbs py-0 text-sm font-normal mt-16 md:mt-24">
        <ul>
          <li className="text-[#081120] font-paragraph text-sm">
            <Link href="/">Home</Link>
          </li>
          <li className="text-[#6C737F] font-paragraph text-sm">
            Terms of Service
          </li>
        </ul>
      </div>
      <div className="pp mb-10  md:mb-24 mt-6 md:mt-10 border rounded-lg p-4 md:p-8">
        <div className="font-title text-3xl mb-6 pp-title font-bold">
          Terms of Service
        </div>
        <div className="subtitle mb-4">Terms of Service:</div>
        <div className="privacy-text mb-6">
          By accessing and placing an order with GoodTools.Ai, you confirm that
          you are in agreement with and bound by the terms of service contained
          in the Terms & Conditions outlined below. These terms apply to the
          entire website and any email or other type of communication between
          you and GoodTools.Ai <br />
          <br />
          Under no circumstances shall GoodTools.Ai team be liable for any
          direct, indirect, special, incidental or consequential damages,
          including, but not limited to, loss of data or profit, arising out of
          the use, or the inability to use, the materials on this site, even if
          GoodTools.Ai team or an authorized representative has been advised of
          the possibility of such damages. If your use of materials from this
          site results in the need for servicing, repair or correction of
          equipment or data, you assume any costs thereof.
          <br />
          <br />
          GoodTools.Ai will not be responsible for any outcome that may occur
          during the course of usage of our resources. We reserve the rights to
          change prices and revise the resources usage policy in any moment.
          This Terms & Conditions was created with Termify.
        </div>
        <div className="subtitle mb-4">License:</div>
        <div className="privacy-text mb-6">
          GoodTools.Ai grants you a revocable, non-exclusive, non-transferable,
          limited license to download, install and use the website strictly in
          accordance with the terms of this Agreement.
          <br /> <br />
          These Terms & Conditions are a contract between you and GoodTools.Ai
          (referred to in these Terms & Conditions as "GoodTools.Ai", "us", "we"
          or "our"), the provider of the GoodTools.Ai website and the services
          accessible from the GoodTools.Ai website (which are collectively
          referred to in these Terms & Conditions as the "GoodTools.Ai
          Service").
          <br />
          <br />
          You are agreeing to be bound by these Terms & Conditions. If you do
          not agree to these Terms & Conditions, please do not use the
          GoodTools.Ai Service. In these Terms & Conditions, "you" refers both
          to you as an individual and to the entity you represent. If you
          violate any of these Terms & Conditions, we reserve the right to
          cancel your account or block access to your account without notice.
        </div>
        <div className="subtitle mb-4">Definitions and key terms:</div>
        <div className="privacy-text mb-6  ">
          To help explain things as clearly as possible in this Terms &
          Conditions, every time any of these terms are referenced, are strictly
          defined as: <br />
          <br />
          <ul>
            <li className="list-item">
              Cookie: small amount of data generated by a website and saved by
              your web browser. It is used to identify your browser, provide
              analytics, remember information about you such as your language
              preference or login information.
            </li>
            <li className="list-item">
              Company: when this terms mention “Company,” “we,” “us,” or “our,”
              it refers to Vivek Varma, (Ashok Nagar, Bangalore, 560025), that
              is responsible for your information under this Terms & Conditions.
            </li>
            <li className="list-item">
              Country: where GoodTools.Ai or the owners/founders of GoodTools.Ai
              are based, in this case is India
            </li>
            <li className="list-item">
              Device: any internet connected device such as a phone, tablet,
              computer or any other device that can be used to visit
              GoodTools.Ai and use the services.
            </li>
            <li className="list-item">
              Service: refers to the service provided by GoodTools.Ai as
              described in the relative terms (if available) and on this
              platform.
            </li>
            <li className="list-item">
              Third-party service: refers to advertisers, contest sponsors,
              promotional and marketing partners, and others who provide our
              content or whose products or services we think may interest you.
            </li>
          </ul>
        </div>
        <div className="subtitle mb-4">Restrictions:</div>
        <div className="privacy-text mb-6  ">
          You agree not to, and you will not permit others to:
          <ul className="mt-4">
            <li className="list-item">
              License, sell, rent, lease, assign, distribute, transmit, host,
              outsource, disclose or otherwise commercially exploit the website
              or make the platform available to any third party.
            </li>
            <li className="list-item">
              Modify, make derivative works of, disassemble, decrypt, reverse
              compile or reverse engineer any part of the website.
            </li>
            <li className="list-item">
              Remove, alter or obscure any proprietary notice (including any
              notice of copyright or trademark) of GoodTools.Ai or its
              affiliates, partners, suppliers or the licensors of the website.
            </li>
          </ul>
        </div>

        <div className="subtitle mb-4">Payment:</div>
        <div className="privacy-text mb-6  ">
          If you pay for any of our one-time payment plans, you agree to pay all
          fees or charges to your account for the Service in accordance with the
          fees, charges and billing terms in effect at the time that each fee or
          charge is due and payable. Your Payment Provider agreement governs
          your use of the designated credit card account, and you must refer to
          that agreement and not these Terms to determine your rights and
          liabilities with respect to your Payment Provider. By providing
          GoodTools.Ai with your credit card number and associated payment
          information, you agree that GoodTools.Ai is authorized to verify
          information immediately, and subsequently invoice your account for all
          fees and charges due and payable to GoodTools.Ai hereunder and that no
          additional notice or consent is required. You agree to immediately
          notify GoodTools.Ai of any change in your billing address or the
          credit card used for payment hereunder. GoodTools.Ai reserves the
          right at any time to change its prices and billing methods, either
          immediately upon posting on our Site or by e-mail delivery to your
          organization’s administrator(s).
          <br />
          <br />
          Any attorney fees, court costs, or other costs incurred in collection
          of delinquent undisputed amounts shall be the responsibility of and
          paid for by you.
          <br />
          <br />
          No contract will exist between you and GoodTools.Ai for the Service
          until GoodTools.Ai accepts your order by a confirmatory e-mail,
          SMS/MMS message, or other appropriate means of communication.
          <br />
          <br />
          You are responsible for any third-party fees that you may incur when
          using the Service.
        </div>
        <div className="subtitle mb-4">Return and Refund Policy:</div>
        <div className="privacy-text mb-6  ">
          Thanks for shopping at GoodTools.Ai. We appreciate the fact that you
          like to buy the stuff we build. We also want to make sure you have a
          rewarding experience while you’re exploring, evaluating, and
          purchasing our products.
          <br />
          <br />
          As with any shopping experience, there are terms and conditions that
          apply to transactions at GoodTools.Ai. We’ll be as brief as our
          attorneys will allow. The main thing to remember is that by placing an
          order or making a purchase at GoodTools.Ai, you agree to the terms
          along with GoodTools.Ai Privacy Policy.
          <br />
          <br />
          If, for any reason, You are not completely satisfied with any good or
          service that we provide, don't hesitate to contact us and we will
          discuss any of the issues you are going through with our product.
        </div>
        <div className="subtitle mb-4">Your Suggestions:</div>
        <div className="privacy-text mb-6  ">
          Any feedback, comments, ideas, improvements or suggestions
          (collectively, "Suggestions") provided by you to GoodTools.Ai with
          respect to the website shall remain the sole and exclusive property of
          GoodTools.Ai.
          <br />
          <br />
          GoodTools.Ai shall be free to use, copy, modify, publish, or
          redistribute the Suggestions for any purpose and in any way without
          any credit or any compensation to you.
        </div>

        <div className="subtitle mb-4">Your Consent:</div>
        <div className="privacy-text mb-6  ">
          We've updated our Terms & Conditions to provide you with complete
          transparency into what is being set when you visit our site and how
          it's being used. By using our website, registering an account, or
          making a purchase, you hereby consent to our Terms & Conditions.
        </div>
        <div className="subtitle mb-4">Links to Other Websites:</div>
        <div className="privacy-text mb-6  ">
          This Terms & Conditions applies only to the Services. The Services may
          contain links to other websites not operated or controlled by
          GoodTools.Ai. We are not responsible for the content, accuracy or
          opinions expressed in such websites, and such websites are not
          investigated, monitored or checked for accuracy or completeness by us.
          Please remember that when you use a link to go from the Services to
          another website, our Terms & Conditions are no longer in effect. Your
          browsing and interaction on any other website, including those that
          have a link on our platform, is subject to that website’s own rules
          and policies. Such third parties may use their own cookies or other
          methods to collect information about you.
        </div>
        <div className="subtitle mb-4">Cookies:</div>
        <div className="privacy-text mb-6  ">
          GoodTools.Ai uses "Cookies" to identify the areas of our website that
          you have visited. A Cookie is a small piece of data stored on your
          computer or mobile device by your web browser. We use Cookies to
          enhance the performance and functionality of our website but are
          non-essential to their use. However, without these cookies, certain
          functionality like videos may become unavailable or you would be
          required to enter your login details every time you visit the website
          as we would not be able to remember that you had logged in previously.
          Most web browsers can be set to disable the use of Cookies. However,
          if you disable Cookies, you may not be able to access functionality on
          our website correctly or at all. We never place Personally
          Identifiable Information in Cookies.
        </div>
        <div className="subtitle mb-4">Changes To Our Terms & Conditions:</div>
        <div className="privacy-text mb-6  ">
          You acknowledge and agree that GoodTools.Ai may stop (permanently or
          temporarily) providing the Service (or any features within the
          Service) to you or to users generally at GoodTools.Ai sole discretion,
          without prior notice to you. You may stop using the Service at any
          time. You do not need to specifically inform GoodTools.Ai when you
          stop using the Service. You acknowledge and agree that if GoodTools.Ai
          disables access to your account, you may be prevented from accessing
          the Service, your account details or any files or other materials
          which is contained in your account.
          <br />
          <br />
          If we decide to change our Terms & Conditions, we will post those
          changes on this page, and/or update the Terms & Conditions
          modification date below.
        </div>
        <div className="subtitle mb-4">Modifications to Our website:</div>
        <div className="privacy-text mb-6  ">
          GoodTools.Ai reserves the right to modify, suspend or discontinue,
          temporarily or permanently, the website or any service to which it
          connects, with or without notice and without liability to you.
        </div>
        <div className="subtitle mb-4">Updates to Our website:</div>
        <div className="privacy-text mb-6  ">
          GoodTools.Ai may from time to time provide enhancements or
          improvements to the features/ functionality of the website, which may
          include patches, bug fixes, updates, upgrades and other modifications
          ("Updates").
          <br />
          <br />
          Updates may modify or delete certain features and/or functionalities
          of the website. You agree that GoodTools.Ai has no obligation to (i)
          provide any Updates, or (ii) continue to provide or enable any
          particular features and/or functionalities of the website to you.
          <br />
          <br />
          You further agree that all Updates will be (i) deemed to constitute an
          integral part of the website, and (ii) subject to the terms and
          conditions of this Agreement.
        </div>
        <div className="subtitle mb-4">Third-Party Services:</div>
        <div className="privacy-text mb-6  ">
          We may display, include or make available third-party content
          (including data, information, applications and other products
          services) or provide links to third-party websites or services
          ("Third- Party Services").
          <br />
          <br />
          You acknowledge and agree that GoodTools.Ai shall not be responsible
          for any Third-Party Services, including their accuracy, completeness,
          timeliness, validity, copyright compliance, legality, decency, quality
          or any other aspect thereof. GoodTools.Ai does not assume and shall
          not have any liability or responsibility to you or any other person or
          entity for any Third-Party Services.
          <br />
          <br />
          Third-Party Services and links thereto are provided solely as a
          convenience to you and you access and use them entirely at your own
          risk and subject to such third parties' terms and conditions.
        </div>
        <div className="subtitle mb-4">Term and Termination:</div>
        <div className="privacy-text mb-6  ">
          This Agreement shall remain in effect until terminated by you or
          GoodTools.Ai. GoodTools.Ai may, in its sole discretion, at any time
          and for any or no reason, suspend or terminate this Agreement with or
          without prior notice.
          <br />
          <br />
          This Agreement will terminate immediately, without prior notice from
          GoodTools.Ai, in the event that you fail to comply with any provision
          of this Agreement. You may also terminate this Agreement by deleting
          the website and all copies thereof from your computer. Upon
          termination of this Agreement, you shall cease all use of the website
          and delete all copies of the website from your computer.
          <br />
          <br />
          Termination of this Agreement will not limit any of GoodTools.Ai
          rights or remedies at law or in equity in case of breach by you
          (during the term of this Agreement) of any of your obligations under
          the present Agreement.
        </div>
        <div className="subtitle mb-4">Copyright Infringement Notice:</div>
        <div className="privacy-text mb-6  ">
          If you are a copyright owner or such owner’s agent and believe any
          material on our website constitutes an infringement on your copyright,
          please contact us setting forth the following information: (a) a
          physical or electronic signature of the copyright owner or a person
          authorized to act on his behalf; (b) identification of the material
          that is claimed to be infringing; (c) your contact information,
          including your address, telephone number, and an email; (d) a
          statement by you that you have a good faith belief that use of the
          material is not authorized by the copyright owners; and (e) the a
          statement that the information in the notification is accurate, and,
          under penalty of perjury you are authorized to act on behalf of the
          owner.
        </div>
        <div className="subtitle mb-4">Limitation of Liability:</div>
        <div className="privacy-text mb-6  ">
          Notwithstanding any damages that you might incur, the entire liability
          of GoodTools.Ai and any of its suppliers under any provision of this
          Agreement and your exclusive remedy for all of the foregoing shall be
          limited to the amount actually paid by you for the website.
          <br />
          <br />
          To the maximum extent permitted by applicable law, in no event shall
          GoodTools.Ai or its suppliers be liable for any special, incidental,
          indirect, or consequential damages whatsoever (including, but not
          limited to, damages for loss of profits, for loss of data or other
          information, for business interruption, for personal injury, for loss
          of privacy arising out of or in any way related to the use of or
          inability to use the website, third-party software and/or third-party
          hardware used with the website, or otherwise in connection with any
          provision of this Agreement), even if GoodTools.Ai or any supplier has
          been advised of the possibility of such damages and even if the remedy
          fails of its essential purpose.
          <br />
          <br />
          Some states/jurisdictions do not allow the exclusion or limitation of
          incidental or consequential damages, so the above limitation or
          exclusion may not apply to you.
        </div>
        <div className="subtitle mb-4">Severability:</div>
        <div className="privacy-text mb-6  ">
          If any provision of this Agreement is held to be unenforceable or
          invalid, such provision will be changed and interpreted to accomplish
          the objectives of such provision to the greatest extent possible under
          applicable law and the remaining provisions will continue in full
          force and effect.
          <br />
          <br />
          This Agreement, together with the Privacy Policy and any other legal
          notices published by GoodTools.Ai on the Services, shall constitute
          the entire agreement between you and GoodTools.Ai concerning the
          Services. If any provision of this Agreement is deemed invalid by a
          court of competent jurisdiction, the invalidity of such provision
          shall not affect the validity of the remaining provisions of this
          Agreement, which shall remain in full force and effect. No waiver of
          any term of this Agreement shall be deemed a further or continuing
          waiver of such term or any other term, and GoodTools.Ai failure to
          assert any right or provision under this Agreement shall not
          constitute a waiver of such right or provision. YOU AND GoodTools.Ai
          AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE
          SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION
          ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.
        </div>
        <div className="subtitle mb-4">Amendments to this Agreement:</div>
        <div className="privacy-text mb-6  ">
          GoodTools.Ai reserves the right, at its sole discretion, to modify or
          replace this Agreement at any time. If a revision is material we will
          provide at least 30 days' notice prior to any new terms taking effect.
          What constitutes a material change will be determined at our sole
          discretion.
          <br />
          <br />
          By continuing to access or use our website after any revisions become
          effective, you agree to be bound by the revised terms. If you do not
          agree to the new terms, you are no longer authorized to use
          GoodTools.Ai.
        </div>
        <div className="subtitle mb-4">Submissions and Privacy:</div>
        <div className="privacy-text mb-6  ">
          In the event that you submit or post any ideas, creative suggestions,
          designs, photographs, information, advertisements, data or proposals,
          including ideas for new or improved products, services, features,
          technologies or promotions, you expressly agree that such submissions
          will automatically be treated as non-confidential and non-proprietary
          and will become the sole property of GoodTools.Ai without any
          compensation or credit to you whatsoever. GoodTools.Ai and its
          affiliates shall have no obligations with respect to such submissions
          or posts and may use the ideas contained in such submissions or posts
          for any purposes in any medium in perpetuity, including, but not
          limited to, developing, manufacturing, and marketing products and
          services using such ideas.
        </div>
        <div className="subtitle mb-4">Promotions:</div>
        <div className="privacy-text mb-6  ">
          GoodTools.Ai may, from time to time, include contests, promotions,
          sweepstakes, or other activities (“Promotions”) that require you to
          submit material or information concerning yourself. Please note that
          all Promotions may be governed by separate rules that may contain
          certain eligibility requirements, such as restrictions as to age and
          geographic location. You are responsible to read all Promotions rules
          to determine whether or not you are eligible to participate. If you
          enter any Promotion, you agree to abide by and to comply with all
          Promotions Rules.
          <br />
          <br />
          Additional terms and conditions may apply to purchases of goods or
          services on or through the Services, which terms and conditions are
          made a part of this Agreement by this reference.
        </div>
        <div className="subtitle mb-4">Typographical Errors:</div>
        <div className="privacy-text mb-6  ">
          In the event a product and/or service is listed at an incorrect price
          or with incorrect information due to typographical error, we shall
          have the right to refuse or cancel any orders placed for the product
          and/or service listed at the incorrect price. We shall have the right
          to refuse or cancel any such order whether or not the order has been
          confirmed and your credit card charged. If your credit card has
          already been charged for the purchase and your order is canceled, we
          shall immediately issue a credit to your credit card account or other
          payment account in the amount of the charge.
        </div>
        <div className="subtitle mb-4">Miscellaneous:</div>
        <div className="privacy-text mb-6  ">
          If for any reason a court of competent jurisdiction finds any
          provision or portion of these Terms & Conditions to be unenforceable,
          the remainder of these Terms & Conditions will continue in full force
          and effect. Any waiver of any provision of these Terms & Conditions
          will be effective only if in writing and signed by an authorized
          representative of GoodTools.Ai. GoodTools.Ai will be entitled to
          injunctive or other equitable relief (without the obligations of
          posting any bond or surety) in the event of any breach or anticipatory
          breach by you. GoodTools.Ai operates and controls the GoodTools.Ai
          Service from its offices in India. The Service is not intended for
          distribution to or use by any person or entity in any jurisdiction or
          country where such distribution or use would be contrary to law or
          regulation. Accordingly, those persons who choose to access the
          GoodTools.Ai Service from other locations do so on their own
          initiative and are solely responsible for compliance with local laws,
          if and to the extent local laws are applicable. These Terms &
          Conditions (which include and incorporate the GoodTools.Ai Privacy
          Policy) contains the entire understanding, and supersedes all prior
          understandings, between you and GoodTools.Ai concerning its subject
          matter, and cannot be changed or modified by you. The section headings
          used in this Agreement are for convenience only and will not be given
          any legal import.
        </div>
        <div className="subtitle mb-4">Disclaimer:</div>
        <div className="privacy-text mb-6  ">
          GoodTools.Ai is not responsible for any content, code or any other
          imprecision. GoodTools.Ai does not provide warranties or guarantees.
          In no event shall GoodTools.Ai be liable for any special, direct,
          indirect, consequential, or incidental damages or any damages
          whatsoever, whether in an action of contract, negligence or other
          tort, arising out of or in connection with the use of the Service or
          the contents of the Service. The Company reserves the right to make
          additions, deletions, or modifications to the contents on the Service
          at any time without prior notice.
          <br />
          <br />
          The GoodTools.Ai Service and its contents are provided "as is" and "as
          available" without any warranty or representations of any kind,
          whether express or implied. GoodTools.Ai is a distributor and not a
          publisher of the content supplied by third parties; as such,
          GoodTools.Ai exercises no editorial control over such content and
          makes no warranty or representation as to the accuracy, reliability or
          currency of any information, content, service or merchandise provided
          through or accessible via the GoodTools.Ai Service. Without limiting
          the foregoing, GoodTools.Ai specifically disclaims all warranties and
          representations in any content transmitted on or in connection with
          the GoodTools.Ai Service or on sites that may appear as links on the
          GoodTools.Ai Service, or in the products provided as a part of, or
          otherwise in connection with, the GoodTools.Ai Service, including
          without limitation any warranties of merchantability, fitness for a
          particular purpose or non-infringement of third party rights. No oral
          advice or written information given by GoodTools.Ai or any of its
          affiliates, employees, officers, directors, agents, or the like will
          create a warranty. Price and availability information is subject to
          change without notice. Without limiting the foregoing, GoodTools.Ai
          does not warrant that the GoodTools.Ai Service will be uninterrupted,
          uncorrupted, timely, or error-free.
        </div>
        <div className="subtitle mb-4">Contact Us:</div>
        <div className="privacy-text mb-6  ">
          Don't hesitate to contact us if you have any questions.
          <ul>
            <li className="list-item">Via Email: contact@spineedge.com</li>
          </ul>
        </div>
      </div>
    </PageWraper>
  );
};

export default Terms;
